# Generated by Django 4.2.3 on 2023-07-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='copy',
            name='rented',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
