# Generated by Django 4.2.3 on 2023-07-07 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copys', '0002_alter_copy_created_date_alter_copy_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='copy',
            options={},
        ),
    ]
