# Generated by Django 4.2.3 on 2023-07-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copys', '0003_alter_copy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='copy',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
