# Generated by Django 4.2.3 on 2023-07-07 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copys', '0004_copy_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 11, 19, 7, 58, 79134, tzinfo=datetime.timezone.utc)),
        ),
    ]
