# Generated by Django 4.2.3 on 2023-07-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copys', '0005_alter_copy_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy',
            name='end_date',
            field=models.DateField(),
        ),
    ]
