# Generated by Django 4.2.3 on 2023-07-10 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copys', '0006_alter_copy_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copy',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='copy',
            name='end_date',
        ),
    ]
