# Generated by Django 4.2.3 on 2023-07-06 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='end_blocked_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 10, 17, 54, 9, 485504, tzinfo=datetime.timezone.utc)),
        ),
    ]
