# Generated by Django 4.2.3 on 2023-07-11 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 15, 14, 8, 31, 226239, tzinfo=datetime.timezone.utc)),
        ),
    ]
