# Generated by Django 4.2.3 on 2023-07-10 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('copys', '0007_remove_copy_created_date_remove_copy_end_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0002_alter_loan_copy_alter_loan_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='copy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='copys.copy'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL),
        ),
    ]
