# Generated by Django 4.2.3 on 2023-07-07 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0010_alter_loan_end_blocked_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='end_blocked_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 11, 18, 45, 35, 534823, tzinfo=datetime.timezone.utc)),
        ),
    ]
